### ISSUE TITLE
testing script print too much lines

### ISSUE THREAD

**Issue by EricTing** [Yeahhhh/geauxdock_multibackend#1]
by running
```
$ bash dock.bash
```
There are too many lines of outputs, which is difficult to check the results.
![qq20150603-1](https://cloud.githubusercontent.com/assets/2810747/7970927/dcd3db22-0a06-11e5-8bd7-390cb73a66cc.png)
Can you limit the output to just a few lines?

**Comment by Yeahhhh** [comment]
The screen output is simplified. see my github.

My code has neither result analysis, nor H5 dump, and is therefore useless
for end users. You might duplicate a branch on your repository and add
these essential features.
